version: "3.8"
services:
  app:
    image: registry.digitalocean.com/ecaz-xyz/app:${TAG}
    build:
      context: .
    ports:
      - "80:8080"
    environment:
      DEBUG: "1"
      PROD: "0"
      TESTING: "1"

      POSTGRES_DB: "postgres"

      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "5432"
      POSTGRES_SSL: "0"
      POSTGRES_USER: "postgres"
      SECRET_KEY: "${SECRET_KEY}"
    volumes:
      - ./app:/app

  db:
    image: postgres:15.5-bookworm
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      default:
        aliases:
          - "${POSTGRES_HOST}"
