version: "3.8"
services:
  app:
    image: registry.digitalocean.com/ecaz-xyz/app
    build:
      context: .
    environment: &env
      DEBUG: "1"
      PROD: "0"
      TESTING: "1"
      MAIL_DEFAULT_SENDER: "admin@ecaz.xyz"
      MAIL_PASSWORD: ""
      MAIL_SERVER: "localhost"
      MAIL_USERNAME: ""
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "db"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_PORT: "5432"
      POSTGRES_SSL: "0"
      POSTGRES_USER: "postgres"
      SECRET_KEY: "1234"
    ports:
      - "80:8080"
    volumes:
      - ./app:/app

  db:
    image: postgres:15.5-bookworm
    environment: *env
    networks:
      default:
        aliases:
          - db