version: "3.8"
services:
  app:
    extends:
      file: base.yml
      service: app
    build:
      context: .
    environment:
      DEBUG: "1"
      PROD: "0"
      TESTING: "1"
      SECRET_KEY: "${SECRET_KEY}"
    volumes:
      - ./app:/app
