version: "3.8"
services:
  app:
    build:
      context: .
    environment: &env
      DEBUG: "1"
      PROD: "0"
      TESTING: "1"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "db"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_PORT: "5432"
      POSTGRES_SSL: "0"
      POSTGRES_USER: "postgres"
      SECRET_KEY: "1234"
    entrypoint: "tox"

  db:
    image: postgres:15.5-bookworm
    environment: *env
    networks:
      default:
        aliases:
          - db